services:
  asf:
    image: justarchi/archisteamfarm:latest
    container_name: asf
    ports:
      - "1242:1242"
    volumes:
      - ${CONTAINER_ROOT}/ASF/config:/app/config
      - ${CONTAINER_ROOT}/ASF/plugins:/app/plugins
      - ${CONTAINER_ROOT}/ASF/logs:/app/logs
    env_file:
      - ../_shared/common.env
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: docker.io/jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    #network_mode: host # hopefully fixes slow connection issue :/ ps..wasn't a slow connection issue
    env_file:
      - ../_shared/common.env
    ports:
      - 800:80
      - 81:81
      - 443:443
    volumes:
      - ${CONTAINER_ROOT}/nginx/data:/data
      - ${CONTAINER_ROOT}/nginx/letsencrypt:/etc/letsencrypt
